# Generated by Django 4.1.7 on 2023-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking_table',
            index=models.Index(fields=['name'], name='restaurant__name_104016_idx'),
        ),
    ]
