# Generated by Django 4.2 on 2023-06-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_category_menu_table_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_table',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.category'),
        ),
    ]
