# Generated by Django 4.2 on 2023-06-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menu_table_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_table',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Menu_table',
        ),
    ]
