# Generated by Django 4.2 on 2023-06-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_category_menu_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu_table',
        ),
    ]
