# Generated by Django 4.2 on 2023-06-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_menu_table_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_table',
            name='category',
        ),
    ]
