# Generated by Django 4.2 on 2023-06-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_menu_table_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
