# Generated by Django 4.2 on 2023-06-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='menuitem_id',
            new_name='menu_table_id',
        ),
    ]
