# Generated by Django 4.2 on 2023-07-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10),
        ),
    ]
